#!/usr/bin/env sh
# ============================================================
#  macOS-native build pipeline (no WSL, no Windows).
#  Produces ONE .dmg per architecture:
#    native/installer/zaalis-macos-arm64.dmg   (Apple Silicon: M1/M2/M3...)
#    native/installer/zaalis-macos-x64.dmg     (Intel)
#
#  Run this on a Mac (or a macOS CI runner). Requires: node, npx, hdiutil.
# ============================================================
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

INSTALLER="$ROOT/native/installer"
mkdir -p "$INSTALLER"

# Must match the Node runtime embedded by @yao-pkg/pkg for node22-macos-*.
PKG_NODE_VERSION="22.23.1"
NODE_GYP_VERSION="13.0.1"

rebuild_pty() {
  pty_arch="$1"
  pty_clang_arch="$pty_arch"
  [ "$pty_arch" = "x64" ] && pty_clang_arch="x86_64"
  pty_cxx_std="${PTY_CXX_STD:-c++17}"
  shift
  (
    cd "$ROOT/node_modules/node-pty"
    # node-gyp reuses generated dependency files across target architectures;
    # a stale partial build can make clang look for a missing .d.raw file.
    # This directory is derived output and is regenerated by node-gyp below.
    rm -rf build
    # node-gyp@13 can throw a spurious "ENOENT ... build/node_gyp_bins" AFTER it
    # has already linked pty.node (flaky under Node 24+). That non-zero exit
    # would abort the whole DMG build even though the native module is correct.
    # We therefore ignore node-gyp's exit code and instead trust the verified
    # artifact: pty.node must exist AND be the requested architecture.
    CXXFLAGS="-std=$pty_cxx_std -arch $pty_clang_arch -Wno-missing-field-initializers -Wno-cast-function-type-mismatch" LDFLAGS="-arch $pty_clang_arch" \
      npm exec --yes --package="node-gyp@$NODE_GYP_VERSION" -- \
      node-gyp rebuild --arch="$pty_arch" "$@" || echo "    (node-gyp exited non-zero; verifying artifact instead)"
    node_out="build/Release/pty.node"
    if [ ! -f "$node_out" ]; then
      echo "ERROR: node-pty build produced no $node_out for $pty_arch" >&2
      exit 1
    fi
    if ! file "$node_out" | grep -q "$pty_clang_arch"; then
      echo "ERROR: $node_out is not $pty_clang_arch: $(file "$node_out")" >&2
      exit 1
    fi
    echo "    - node-pty ok ($pty_clang_arch): $node_out"
  )
}

# Each target needs a node-pty binary built for the Node 22 runtime embedded
# by pkg. Restore the developer runtime's ABI when the script exits so a
# successful cross-build never leaves `npm test` or the local IDE unusable.
restore_host_pty() {
  echo "Restoring node-pty for the local Node runtime..."
  host_arch=$(uname -m)
  [ "$host_arch" = "x86_64" ] && host_arch="x64"
  PTY_CXX_STD=c++20 rebuild_pty "$host_arch" || echo "WARNING: local node-pty restore failed; rebuild node-pty before running the local IDE."
}
trap restore_host_pty EXIT

# package_macos_electron.sh adds the application payload after Electron's
# original signature was created. Re-sign the completed bundle before it is
# placed in the DMG so macOS can verify its resources. Supplying
# MACOS_CODESIGN_IDENTITY uses a Developer ID identity in CI/release builds;
# local builds use a verifiable ad-hoc signature.
sign_app() {
  app="$1"
  identity="${MACOS_CODESIGN_IDENTITY:--}"
  echo "    - signing application bundle (${identity})"
  codesign --force --deep --sign "$identity" "$app"
  codesign --verify --deep --strict "$app"
}

VERSION=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$ROOT/package.json" | head -n 1)
VERSION=${VERSION:-1.0.0}

if ! command -v cargo >/dev/null 2>&1; then
  echo "ERROR: cargo not found. The Rust core (zaalis-agentd) is required." >&2
  echo "       Install Rust: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" >&2
  exit 1
fi
# Chaque DMG est mono-architecture : la cible Rust correspondante doit etre
# installee, meme quand on construit l'autre architecture depuis ce Mac.
rustup target add aarch64-apple-darwin x86_64-apple-darwin >/dev/null 2>&1 || true

echo "[1/3] Preparing Electron icon (.icns)..."
npm run check:mojibake
node native/make_icns.js

build_arch() {
  arch="$1"          # x64 | arm64
  pkg_target="$2"    # node22-macos-x64 | node22-macos-arm64
  rust_target="aarch64-apple-darwin"
  [ "$arch" = "x64" ] && rust_target="x86_64-apple-darwin"

  serverdist="native/dist-macos-${arch}-server"
  dist="native/dist-macos-${arch}"
  zip="native/.electron-cache/electron-darwin-${arch}.zip"

  echo "==> Building macOS ${arch}"
  rm -rf "$serverdist" "$dist"
  mkdir -p "$serverdist/bin"

  # node-pty is a native module used by the integrated terminal. Rebuild it
  # for each target before pkg snapshots the server, otherwise an Intel DMG
  # made on Apple Silicon would contain the wrong .node binary.
  echo "    - rebuilding terminal native module (${arch})"
  rebuild_pty "$arch" \
    --target="$PKG_NODE_VERSION" \
    --dist-url="https://nodejs.org/download/release"

  echo "    - packaging server"
  npx pkg . --no-bytecode --public --public-packages "*" \
    --targets "$pkg_target" --output "$serverdist/zaalis-server"

  # Le CLI livre est celui du coeur Rust, comme sur Windows et Linux : Chat,
  # Agents et le terminal partagent ainsi exactement le meme moteur.
  # zaalis-agentd est indispensable au serveur, donc cette etape n'est pas
  # optionnelle.
  echo "    - building the Rust core (agentd, CLI, sandbox) for ${arch}"
  cargo build --manifest-path rust/Cargo.toml --release --target "$rust_target" \
    -p zaalis-cli -p zaalis-agentd -p zaalis-sandbox-helper

  echo "    - staging the Rust binaries"
  ZAALIS_RUST_RELEASE_DIR="$ROOT/rust/target/$rust_target/release" \
    sh scripts/stage-rust-binaries.sh "$ROOT/$serverdist"

  echo "    - copying assets"
  cp -R interface "$serverdist/interface"
  # A Node native addon cannot reliably be loaded from pkg's virtual snapshot.
  # Ship the freshly rebuilt, architecture-specific PTY next to the server.
  mkdir -p "$serverdist/node_modules"
  cp -R node_modules/node-pty "$serverdist/node_modules/node-pty"
  [ -d image ] && cp -R image "$serverdist/image"
  cp package.json "$serverdist/package.json"
  [ -f README_MACOS.md ] && cp README_MACOS.md "$serverdist/README.txt"

  echo "    - downloading Electron runtime"
  node native/download_electron_macos.js "$arch" "$zip"

  echo "    - assembling .app"
  sh native/package_macos_electron.sh "$ROOT" "$arch" "$ROOT/$serverdist" "$ROOT/$zip" "$ROOT/$dist"

  sign_app "$ROOT/$dist/zaalis IDE.app"

  echo "    - building .dmg"
  sh native/make_dmg.sh \
    "$ROOT/$dist/zaalis IDE.app" \
    "$INSTALLER/zaalis-macos-${arch}.dmg" \
    "zaalis IDE ${VERSION}"
}

echo "[2/3] Building Apple Silicon (arm64) DMG..."
build_arch arm64 node22-macos-arm64

echo "[3/3] Building Intel (x64) DMG..."
build_arch x64 node22-macos-x64

echo
echo "Done. macOS DMGs:"
echo "  $INSTALLER/zaalis-macos-arm64.dmg   (Apple Silicon)"
echo "  $INSTALLER/zaalis-macos-x64.dmg     (Intel)"
