/* Aide affichée dans la fenêtre « Aide & documentation ». */
window.HELP_TOPICS = [
  { q: "C'est quoi une IA (modèle de langage) ?", a: "Un modèle de langage est un programme entraîné à produire du texte à partir d'un contexte. Dans zaalis, il peut expliquer du code, proposer des changements et utiliser les outils que tu autorises. Il peut se tromper : vérifie ses réponses et les modifications importantes." },
  { q: "Modèle cloud ou local : quelle différence ?", a: "Un modèle cloud fonctionne sur les serveurs d'un fournisseur et demande une connexion Internet. Un modèle local fonctionne sur ton ordinateur avec Ollama ou un fichier GGUF ; sa vitesse dépend de ton matériel. Vérifie les conditions et les quotas du fournisseur pour les modèles cloud." },
  { q: "Comment choisir un modèle ?", a: "Choisis d'abord selon la tâche : code complexe, analyse d'image, réponse rapide ou confidentialité locale. Vérifie ensuite que le modèle accepte les outils et les images dont tu as besoin. La liste des modèles disponibles dépend du compte ou de la clé configurés." },
  { q: "Comment écrire un bon prompt ?", a: "Donne quatre éléments : l'objectif, le contexte, les contraintes et le résultat attendu. Exemple : « Corrige le bouton Enregistrer dans cette page. Garde le style actuel, ne touche pas aux autres écrans, puis indique les fichiers modifiés et ce que tu as vérifié. » Un objectif précis évite les changements inutiles." },
  { q: "Comment demander une modification de code sans tout casser ?", a: "Nomme le fichier ou l'écran concerné, décris le comportement actuel et le comportement souhaité. Ajoute ce qu'il faut préserver, par exemple les données, les styles et les autres fonctions. Demande une vérification adaptée au changement et un résumé des limites restantes." },
  { q: "Comment améliorer une réponse qui ne me convient pas ?", a: "Explique ce qui manque ou ce qui est faux avec un exemple concret. Tu peux demander : « Garde la solution, mais raccourcis l'explication », « Vérifie ce point dans le fichier » ou « Reprends seulement la partie connexion ». Tu n'as pas besoin de repartir de zéro." },
  { q: "À quoi servent le contexte et les tokens ?", a: "Le contexte rassemble les messages et les informations du projet que le modèle reçoit. Les tokens sont les unités utilisées pour mesurer ce contenu. Chaque modèle a une limite ; l'indicateur sous le sélecteur montre l'espace utilisé. Sur une longue discussion, rappelle les contraintes essentielles." },
  { q: "À quoi sert le raisonnement ?", a: "Certains modèles acceptent un niveau d'effort pour les tâches difficiles. Un niveau élevé peut prendre plus de temps ou consommer plus de quota. Le réglage proposé dépend du modèle choisi." },
  { q: "Comment joindre une image à une demande ?", a: "Utilise le bouton d'ajout de pièce jointe, puis décris ce que tu veux examiner dans l'image. Le modèle sélectionné doit prendre en charge la vision. Pour une capture d'écran, indique l'élément précis et le résultat souhaité." },
  { q: "C'est quoi la quantification (Q4, Q6, Q8) ?", a: "La quantification réduit la taille d'un modèle local. Q4 demande généralement moins de mémoire, tandis que Q6 et Q8 gardent davantage de précision au prix de fichiers plus lourds. Le bon choix dépend de la mémoire disponible et de la qualité attendue." },
  { q: "C'est quoi GGUF et Ollama ?", a: "GGUF est un format de fichier pour les modèles locaux. zaalis peut lancer un fichier GGUF avec son moteur intégré. Ollama est un autre moteur local qui gère ses propres modèles. Choisis le moteur correspondant au modèle que tu as installé." },
  { q: "À quoi servent les modes d'autorisation et les agents ?", a: "Le mode d'autorisation règle quand zaalis te demande de valider une action. Le mode Agents répartit une tâche entre plusieurs modèles. Pour un projet sensible, décris les fichiers à préserver et vérifie les actions proposées avant de les accepter." }
];
